### ISSUE TITLE
Rename Scenarios and Use Cases

### ISSUE THREAD

**Issue by Fredericson** [scenarioo/scenarioo-example-swtbot-e4#9]

**Comment by bruderol** [comment]
Better "Import Order" because the seems to be the real "user goal" that the user wants to achieve, or not? Maybe i not understand the application yet.

**Comment by bruderol** [comment]
Please consider my more detailed feedback in Yammer Thread where I listed other detailed proposals on how to improve your test / documentation structure in this example.

**Comment by Fredericson** [comment]
Delete Order: should have an extension in its name, because it not only deletes an Order it also verifies the Order is not anymore available.
Remove Order: should have extension in its name, because it not only removes an Order it also verifies the Order is still available. 
Find Order: will be renamed to Import Order
NoDuplicateOrderInOrderOverview: will be renamed, because it also belongs to the Import Use Case.
